version: '2'
services:
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - 5436:5432